# Generated by Django 3.0.2 on 2021-01-13 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('Id_Apoderado', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Celular', models.IntegerField()),
                ('Correo', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('Id_Asistencia', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bimestre',
            fields=[
                ('Id_Bimestre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Bimestre1', models.IntegerField()),
                ('Bimestre2', models.IntegerField()),
                ('Bimestre3', models.IntegerField()),
                ('Bimestre4', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Asistencia',
            fields=[
                ('Id_Detalle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Asistio', models.CharField(max_length=10)),
                ('Tardanza', models.CharField(max_length=10)),
                ('Falta', models.CharField(max_length=10)),
                ('Falta_Justificada', models.CharField(max_length=10)),
                ('Tardanza_Justificada', models.CharField(max_length=10)),
                ('Fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('Id_Docente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Celular', models.IntegerField()),
                ('Correo', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('Id_Director', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Celular', models.IntegerField()),
                ('Correo', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('Id_Materia', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nombre_Curso', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Salon', models.CharField(max_length=50)),
                ('Grado', models.CharField(max_length=3)),
                ('Seccion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('Id_TipoUsuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo_Familiar',
            fields=[
                ('Id_VinculoFamiliar', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Id_Apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Apoderado')),
                ('Id_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_Notas',
            fields=[
                ('Id_ReporteNotas', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Id_Bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Bimestre')),
                ('Id_Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Docente')),
                ('Id_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Estudiante')),
                ('Id_Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Materia')),
                ('Id_Salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Salon')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte_Asistencia',
            fields=[
                ('Id_ReporteAsistencia', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Id_Asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Asistencias')),
                ('Id_Bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Bimestre')),
                ('Id_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Estudiante')),
                ('Id_Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('Id_Notas', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Id_Bimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Bimestre')),
                ('Id_Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Estudiante')),
                ('Id_Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Salon'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Tipo_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.TipoUsuario'),
        ),
        migrations.AddField(
            model_name='docente',
            name='Materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Materia'),
        ),
        migrations.AddField(
            model_name='docente',
            name='Tipo_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.TipoUsuario'),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('Id_Director', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Celular', models.IntegerField()),
                ('Correo', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Tipo_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.TipoUsuario')),
            ],
        ),
        migrations.AddField(
            model_name='asistencias',
            name='Id_Bimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Bimestre'),
        ),
        migrations.AddField(
            model_name='asistencias',
            name='Id_Detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Detalle_Asistencia'),
        ),
        migrations.AddField(
            model_name='asistencias',
            name='Id_Estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Estudiante'),
        ),
        migrations.AddField(
            model_name='asistencias',
            name='Id_Materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Materia'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='Tipo_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.TipoUsuario'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('Id_Administrador', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Celular', models.IntegerField()),
                ('Correo', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Tipo_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema.TipoUsuario')),
            ],
        ),
    ]
