# Generated by Django 3.0.2 on 2021-01-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='Id_Director',
            new_name='Id_Estudiante',
        ),
    ]
