# Generated by Django 3.0.2 on 2021-01-15 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_notas_id_salonc'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='Id_Salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sistema.Salon'),
            preserve_default=False,
        ),
    ]
