# Generated by Django 3.0.2 on 2021-01-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_materia_id_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='Correo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
