# Generated by Django 3.0.2 on 2021-01-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_auto_20210117_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='Password',
        ),
    ]
