# Generated by Django 3.0.2 on 2021-01-17 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0006_remove_docente_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='Materia',
        ),
        migrations.AddField(
            model_name='materia',
            name='Id_Docente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sistema.Docente'),
            preserve_default=False,
        ),
    ]
