# Generated by Django 3.0.2 on 2021-01-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0007_auto_20210117_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='Id_Docente',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
