# Generated by Django 3.0.2 on 2021-01-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0008_auto_20210117_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='Celular',
        ),
        migrations.AddField(
            model_name='docente',
            name='User',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
