# Generated by Django 3.0.2 on 2021-01-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0009_auto_20210117_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='Correo',
            field=models.CharField(max_length=50),
        ),
    ]
