# Generated by Django 3.0.2 on 2021-01-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0010_auto_20210117_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='Password',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='Celular',
        ),
    ]
