# Generated by Django 3.0.2 on 2021-01-18 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0011_auto_20210117_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='Salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema.Salon'),
        ),
    ]
