# Generated by Django 3.0.2 on 2021-01-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0012_auto_20210117_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte_asistencia',
            name='Id_Asistencia',
        ),
        migrations.RemoveField(
            model_name='reporte_asistencia',
            name='Id_Bimestre',
        ),
        migrations.RemoveField(
            model_name='reporte_asistencia',
            name='Id_Estudiante',
        ),
        migrations.RemoveField(
            model_name='reporte_asistencia',
            name='Id_Materia',
        ),
        migrations.AlterField(
            model_name='docente',
            name='Id_Docente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Asistencias',
        ),
        migrations.DeleteModel(
            name='Detalle_Asistencia',
        ),
        migrations.DeleteModel(
            name='Reporte_Asistencia',
        ),
    ]
