# Generated by Django 3.0.2 on 2021-01-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0013_auto_20210118_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='Id_Estudiante',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
