# Generated by Django 3.0.2 on 2021-01-18 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0014_auto_20210118_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='Id_Bimestre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Sistema.Bimestre'),
        ),
    ]
