# Generated by Django 3.0.2 on 2021-01-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0015_auto_20210118_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='Id_Estudiante',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
